### ISSUE TITLE
Make program automatically output log file

### ISSUE THREAD

**Issue by ctessum** [spatialmodel/inmap#5]
... so that users can send a log file with their question even if they did not save the terminal output to a file.

**Comment by dpaolella** [comment]
fixed in @76f7cbbedb01b336a9dcb3edb52fc1040f87312d

**Comment by acwatt** [comment]
## Phase 5C — Global Convergence at 32 CPUs (GOMAXPROCS=0): First Results

Job 32932408 (all 10 sources, savio3, 32 CPUs, GOMAXPROCS=0, 3-day walltime) is running. Three sources have already converged.

### Completed so far (32 CPUs):

| source | 1 CPU (s) | 32 CPUs (s) | speedup |
|--------|-----------|------------|---------|
| indonesia | 2,535 | **2,635** | ~1× (same) |
| japan_tokyo | 3,568 | **3,170** | 1.12× (nproc=40 on this node¹) |
| eastern_china | 3,896 | **3,853** | ~1× (same) |

¹ One node had 40 CPUs visible to cgroups instead of 32; GOMAXPROCS=0 → 40 goroutines.

### ⚠️ KEY FINDING: 32 CPUs ≈ 1 CPU in wall time

The per-iteration rate at 32 CPUs (~0.27–0.39 s/iter from live logs) matches 1-CPU rate (~0.30 s/iter). 32 CPUs provides **zero wall-time speedup** but costs **32× more SUs**.

### The 8-CPU anomaly (from job 32922837)

- indonesia at 1 CPU: 2,535s
- indonesia at **8 CPUs: 6,293s** (**2.5× SLOWER!**)
- indonesia at 32 CPUs: 2,635s (~same as 1 CPU)

Hypothesis: 8 goroutines on the 1.79M-cell global domain creates the worst-case memory bandwidth contention pattern. At 32 goroutines (full node), the workload is spread across both NUMA sockets, but net throughput is the same as single-threaded due to memory bandwidth saturation.

### Production implication

Running N simultaneous sources with 1 CPU each is ~N× faster and ~same total SU cost as 1 source with N CPUs. The T3-A experiment (#6) will confirm by running [1×32, 2×16, 4×8, 8×4, 16×2, 32×1] on one node.

### Ron benchmarks (for reference)

Global domain, GOMAXPROCS=4, eastern_usa source:
- 10 iter: 301.6s total (gob 279s + census ~5s + iters)
- 100 iter: 408.8s total
- 1000 iter: 1500.3s total → **~1.22 s/iter** stabilized

Savio savio3 at 1 CPU: ~0.30 s/iter → **ron is ~4× slower per iteration than savio3**

Updated results in: `cmd/inmapserver/benchmarks/results/summary.md` (Phases 5C and 5D)
